name: chronocore_companion
description: "Mobile companion app for ChronoCore: Path of Realities"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  http: ^1.4.0
  shared_preferences: ^2.0.15
  socket_io_client: ^3.1.2
  arcore_flutter_plugin: ^0.1.0
  qr_code_scanner: ^1.0.1
  flutter_dotenv: ^5.0.2
  flutter_secure_storage: ^9.2.4
  intl: ^0.20.2
  flutter_svg: ^2.1.0
  qr_flutter: ^4.0.0
  flutter_local_notifications: ^19.2.1
  url_launcher: ^6.1.3
  cached_network_image: ^3.2.1
  flutter_spinkit: ^5.1.0
  path_provider: ^2.0.11
  permission_handler: ^10.0.0
  flutter_markdown: ^0.7.7+1
  uuid: ^4.5.1
  animated_text_kit: ^4.2.2
  google_fonts: ^6.1.0
  mobile_scanner: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - .env
  
  fonts:
    - family: Orbitron
      fonts:
        - asset: assets/fonts/Orbitron-Regular.ttf
          weight: 400
        - asset: assets/fonts/Orbitron-Medium.ttf
          weight: 500
        - asset: assets/fonts/Orbitron-Bold.ttf
          weight: 700
    - family: Exo
      fonts:
        - asset: assets/fonts/Exo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Exo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Exo-Bold.ttf
          weight: 700
